name: Pull Request Build
# For pull requests: builds and test
on:
  push:
    branches:
      - '!master'
      - '!jakartaee8'
  pull_request:
    branches:
      - master
      - jakartaee8
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
      - name: build and test
        run: ./gradlew assemble && ./gradlew check --info --stacktrace
